### ISSUE TITLE
serve fails

### ISSUE THREAD

**Issue by top-master** [mazipan/quran-offline#73]
Executing the `yarn dev` command on `Windows 7` outputs below and just hangs:
```
Admin@Admin-PC MINGW32 ~/Desktop/quran-offline (master)
$ yarn dev
yarn run v1.7.0
$ cross-env NODE_ENV=development nodemon server/index.js --watch server
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Users\Admin\Desktop\quran-offline\server/**/*
[nodemon] starting `node server/index.js`
C:\Users\Admin\Desktop\quran-offline\nuxt.config.js:1
(function (exports, require, module, __filename, __dirname) { import { SurahConstant } from './constant/surah'
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...
```
___
other information:
```
$node --version
v10.15.0

$php --version
PHP 7.3.1 (cli) (built: Jan  9 2019 22:43:14) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by mazipan** [comment]
Fix in latest `master` branch
